# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Adnan Basar
tagline:          'Python and Android Developer'
description:      'Blog about <i>#Android, #Python and #Javascript</i> Development.  <a href="https://twitter.com/adnanbasarr" target="_blank">@adnanbasarr</a>.'
url:              http://adnbsr.com

author:
  name:           'adnbsr'
  url:            https://twitter.com/adnanbasarr

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/adnbsr

plugins:
    - jekyll-paginate          
