# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Adnan Basar
tagline:          'Python and Android Developer'
description:      '#Android, #Python and #Javascript Developer <hr/><a href="https://twitter.com/adnanbasarr" target="_blank">@adnanbasarr</a>'
url:              http://adnbsr.com

author:
  name:           'adnbsr'
  url:            https://twitter.com/adnanbasarr

paginate:         5

plugins:
        - jekyll-paginate

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/adnbsr
